### ISSUE TITLE
aarch64-linux buildbot status?

### ISSUE THREAD

**Issue by mmatyas** [rust-lang/rust-buildbot#101]
So I've wanted to take a look on the AArch64 build testing due to rust-lang/rust#33737, but apparently the bot isn't public? I don't see aarch64 on the builders page, and in https://github.com/rust-lang/rust-buildbot/blob/master/master/master.cfg#L253, it's marked as `NOAUTO`. What does that mean?

**Comment by alexcrichton** [comment]
Oh we don't actually have any bots that are running aarch64 natively, we only have a dist bot that cross compiles to that platform and an auto bot which compiles the standard library. That "NOAUTO" just means that there's not a cross builder we gate on for the auto builds.

So in that sense it's not necessarily private because it doesn't exist :)
